export class IContinentalData {
    continent:string;
    updated:number;
    cases:number;
    todayCases:number;
    deaths:number;
    todayDeaths:number;
    recovered:number;
    todayRecovered:number;
    active:number;
    critical:number;
    casesPerOneMillion:number;
    deathsPerOneMillion:number;
    tests:number;
    testsPerOneMillion:number;
    population:number;
    activePerOneMillion:string;
    recoveredPerOneMillion:number;
    criticalPerOneMillion:number;
}
